<a href="https://colab.research.google.com/github/aky360/A.I./blob/main/Data%20Science/Data%20Analysis/Police_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q. 1) Instruction ( For Data Cleaning ) - Remove the column that only contains missing values.**

**Q. 2) Question ( Based on Filtering + Value Counts ) - For Speeding , were Men or Women stopped more often ?**

**Q. 3) Question ( Groupby ) - Does gender affect who gets searched during a stop ?**
**Question ( mapping + data-type casting )**

**Q. 4) Question ( mapping + data-type casting ) - What is the mean stop_duration ?**

**Q. 5) Question ( Groupby , Describe ) - Compare the age distributions for each violation.**

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/aky360/A.I./main/Data%20Science/Data%20Analysis/Datasets/3.%20Police%20Data.csv"
df = pd.read_csv(url)
df.head()

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [ ]:
print(df.shape)
print(df.size)
print(df.index)
print(df.columns)
print(df.columns.size)
print(df.dtypes)

(65535, 15)
983025
RangeIndex(start=0, stop=65535, step=1)
Index(['stop_date', 'stop_time', 'country_name', 'driver_gender',
       'driver_age_raw', 'driver_age', 'driver_race', 'violation_raw',
       'violation', 'search_conducted', 'search_type', 'stop_outcome',
       'is_arrested', 'stop_duration', 'drugs_related_stop'],
      dtype='object')
15
stop_date              object
stop_time              object
country_name          float64
driver_gender          object
driver_age_raw        float64
driver_age            float64
driver_race            object
violation_raw          object
violation              object
search_conducted         bool
search_type            object
stop_outcome           object
is_arrested            object
stop_duration          object
drugs_related_stop       bool
dtype: object

In [ ]:
df.describe()

       country_name  driver_age_raw    driver_age
count           0.0    61481.000000  61228.000000
mean            NaN     1967.791106     34.148984
std             NaN      121.050106     12.760710
min             NaN        0.000000     15.000000
25%             NaN     1965.000000     23.000000
50%             NaN     1978.000000     31.000000
75%             NaN     1985.000000     43.000000
max             NaN     8801.000000     88.000000

In [ ]:
df.nunique()

stop_date             2651
stop_time             1432
country_name             0
driver_gender            2
driver_age_raw          93
driver_age              73
driver_race              5
violation_raw           12
violation                6
search_conducted         2
search_type             23
stop_outcome             6
is_arrested              2
stop_duration            4
drugs_related_stop       2
dtype: int64

In [ ]:
df.isnull().sum()

stop_date                 0
stop_time                 0
country_name          65535
driver_gender          4061
driver_age_raw         4054
driver_age             4307
driver_race            4060
violation_raw          4060
violation              4060
search_conducted          0
search_type           63056
stop_outcome           4060
is_arrested            4060
stop_duration          4060
drugs_related_stop        0
dtype: int64

**Q. 1) Instruction ( For Data Cleaning ) - Remove the column that only contains missing values.**

---

In [ ]:
df.drop(columns = 'country_name', inplace=True)

In [ ]:
df.head(3)

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

**Q. 2) Question ( Based on Filtering + Value Counts ) - For Speeding , were Men or Women stopped more often ?**

---

In [ ]:
df[df['violation'] == 'Speeding']

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
4,3/14/2005,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
6,4/1/2005,17:30,M,1969.0,36.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65527,12/6/2012,15:26,F,1981.0,31.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
65529,12/6/2012,16:00,M,1994.0,18.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
65530,12/6/2012,17:54,F,1987.0,25.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
65531,12/6/2012,22:22,M,1954.0,58.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
65534,12/7/2012,0:30,F,1985.0,27.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [ ]:
df[df['violation'] == 'Speeding']['driver_gender']

0        M
1        M
2        M
4        F
6        M
        ..
65527    F
65529    M
65530    F
65531    M
65534    F
Name: driver_gender, Length: 37204, dtype: object

In [ ]:
df[df['violation'] == 'Speeding']['driver_gender'].value_counts()

M    25517
F    11686
Name: driver_gender, dtype: int64

In [ ]:
df.groupby('driver_gender')['violation'].value_counts()

driver_gender  violation
F              Speeding               11686
               Moving violation        2142
               Equipment               1396
               Registration/plates      632
               Other                    454
M              Speeding               25517
               Moving violation        9784
               Equipment               5120
               Other                   3129
               Registration/plates     1611
               Seat belt                  3
Name: violation, dtype: int64

In [ ]:
# genders = df.groupby('driver_gender')['violation'].value_counts()
# print(type(genders))
df.groupby(['driver_gender', 'driver_race'])['violation'].value_counts()

driver_gender  driver_race  violation
F              Asian        Speeding                 306
                            Moving violation          33
                            Equipment                 14
                            Other                      7
                            Registration/plates        6
               Black        Speeding                 878
                            Moving violation         279
                            Equipment                276
                            Registration/plates      140
                            Other                     61
               Hispanic     Speeding                 484
                            Moving violation         206
                            Equipment                170
                            Registration/plates      105
                            Other                     49
               Other        Speeding                  17
                            Equipment                  3
                            Moving violation           2
                            Other                      1
               White        Speeding               10001
                            Moving violation        1622
                            Equipment                933
                            Registration/plates      381
                            Other                    336
M              Asian        Speeding                 867
                            Moving violation         209
                            Equipment                116
                            Other                     58
                            Registration/plates       23
               Black        Speeding                2780
                            Moving violation        1797
                            Equipment                986
                            Other                    706
                            Registration/plates      363
                            Seat belt                  1
               Hispanic     Speeding                1578
                            Moving violation        1337
                            Equipment                899
                            Other                    420
                            Registration/plates      362
                            Seat belt                  1
               Other        Speeding                 108
                            Moving violation          47
                            Other                     20
                            Equipment                 12
                            Registration/plates        1
               White        Speeding               20184
                            Moving violation        6394
                            Equipment               3107
                            Other                   1925
                            Registration/plates      862
                            Seat belt                  1
Name: violation, dtype: int64

**Q. 3) Question ( Groupby ) - Does gender affect who gets searched during a stop ? Question ( mapping + data-type casting )**


---

In [ ]:
df[df['search_conducted'] == True]['driver_gender'].value_counts()

M    2113
F     366
Name: driver_gender, dtype: int64

In [ ]:
df.groupby('driver_gender')['search_conducted'].sum()

driver_gender
F     366
M    2113
Name: search_conducted, dtype: int64

In [ ]:
df['search_conducted'].value_counts()

False    63056
True      2479
Name: search_conducted, dtype: int64

**Q. 4) Question ( mapping + data-type casting ) - What is the mean stop_duration ?**

---

In [ ]:
df['stop_duration'].value_counts()

0-15 Min     47379
16-30 Min    11448
30+ Min       2647
2                1
Name: stop_duration, dtype: int64

In [ ]:
df['stop_duration'] = df['stop_duration'].map({'0-15 Min' : 7.5, '16-30 Min' : 24, '30+ Min' : 45})

In [ ]:
df.head(3)

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
1,1/18/2005,8:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
2,1/23/2005,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False

In [ ]:
df['stop_duration'].mean()

12.187420698181345

**Q. 5) Question ( Groupby , Describe ) - Compare the age distributions for each violation.**

---

In [ ]:
df['violation'].describe()

count        61475
unique           6
top       Speeding
freq         37204
Name: violation, dtype: object

In [ ]:
new_df = pd.DataFrame(df['violation'], df['driver_age'])
new_df.head(3)

                   violation
driver_age
20.0                Speeding
40.0               Equipment
33.0        Moving violation

In [ ]:
df['driver_age'].describe()

count    61228.000000
mean        34.148984
std         12.760710
min         15.000000
25%         23.000000
50%         31.000000
75%         43.000000
max         88.000000
Name: driver_age, dtype: float64

In [ ]:
df.groupby('violation')['driver_age'].describe()

,count,mean,std,min,25%,50%,75%,max
violation,,,,,,,,
Equipment,6507.0,31.682957,11.380671,16.0,23.0,28.0,39.0,81.0
Moving violation,11876.0,36.736443,13.258350,15.0,25.0,35.0,47.0,86.0
Other,3477.0,40.362381,12.754423,16.0,30.0,41.0,50.0,86.0
Registration/plates,2240.0,32.656696,11.150780,16.0,24.0,30.0,40.0,74.0
Seat belt,3.0,30.333333,10.214369,23.0,24.5,26.0,34.0,42.0
Speeding,37120.0,33.262581,12.615781,15.0,23.0,30.0,42.0,88.0