<a href="https://colab.research.google.com/github/aky360/A.I./blob/main/Data%20Science/Data%20Analysis1/SqlPandasAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
path = 'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/'
data = pd.read_csv(path + "titanic.csv")
data.head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [2]:
"""
SELECT Survived, Pclass, Name FROM data LIMIT 5;
"""

data[['Survived', 'Pclass', 'Name']].head()

   Survived  Pclass                                               Name
0         0       3                             Mr. Owen Harris Braund
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
2         1       3                              Miss. Laina Heikkinen
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle
4         0       3                            Mr. William Henry Allen

In [3]:
"""
SELECT * FROM data
WHERE Sex = 'male' LIMIT 5
"""

data[data['Sex'] == 'male'].head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
5,0,3,Mr. James Moran,male,27.0,0,0,8.4583
6,0,1,Mr. Timothy J McCarthy,male,54.0,0,0,51.8625
7,0,3,Master. Gosta Leonard Palsson,male,2.0,3,1,21.0750

In [4]:
"""
SELECT * FROM data
WHERE Sex = 'male' AND Age > 5.00;
"""

data[(data['Sex'] == 'male') & (data['Age'] > 5.00)]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
5,0,3,Mr. James Moran,male,27.0,0,0,8.4583
6,0,1,Mr. Timothy J McCarthy,male,54.0,0,0,51.8625
12,0,3,Mr. William Henry Saundercock,male,20.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
879,0,2,Mr. Frederick James Banfield,male,28.0,0,0,10.5000
880,0,3,Mr. Henry Jr Sutehall,male,25.0,0,0,7.0500
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

In [5]:
"""
SELECT Sex, count(*) FROM data
GROUP BY Sex;
"""

data.groupby('Sex').size()

Sex
female    314
male      573
dtype: int64

In [6]:
"""
SELECT * FROM df1
INNER JOIN df2 ON df1.key = df2.key;
"""

import numpy as np
df1 = pd.DataFrame({'key': ['A', 'B', 'C', 'D'],
                     'value': np.random.randn(4)})
print(df1)


df2 = pd.DataFrame({'key': ['B', 'D', 'D', 'E'],
                     'value': np.random.randn(4)})
print(df2)

pd.merge(df1, df2, on='key')

  key     value
0   A  0.768814
1   B  0.436221
2   C  0.339147
3   D  1.265730
  key     value
0   B  0.696362
1   D -0.465142
2   D  0.310060
3   E  2.100262

  key   value_x   value_y
0   B  0.436221  0.696362
1   D  1.265730 -0.465142
2   D  1.265730  0.310060

In [7]:
"""
SELECT * FROM df1
LEFT OUTER JOIN df2 ON df1.key = df2.key;
"""

pd.merge(df1, df2, on='key', how='left')

  key   value_x   value_y
0   A  0.768814       NaN
1   B  0.436221  0.696362
2   C  0.339147       NaN
3   D  1.265730 -0.465142
4   D  1.265730  0.310060

In [8]:
"""
SELECT * FROM df1
RIGHT OUTER JOIN df2 ON df1.key = df2.key;
"""

pd.merge(df1, df2, on='key', how='right')

  key   value_x   value_y
0   B  0.436221  0.696362
1   D  1.265730 -0.465142
2   D  1.265730  0.310060
3   E       NaN  2.100262

In [9]:
"""
SELECT * FROM df1
FULL OUTER JOIN df2 ON df1.key = df2.key;
"""

pd.merge(df1, df2, on='key', how='outer')

  key   value_x   value_y
0   A  0.768814       NaN
1   B  0.436221  0.696362
2   C  0.339147       NaN
3   D  1.265730 -0.465142
4   D  1.265730  0.310060
5   E       NaN  2.100262